type Category {
   id: ID! @unique
   title: String!
   color: String!
   questions: [Question]
}

type Question {
   id: ID! @unique
   points: Int!
   question: String!
   type: String!
   category: String!
   answer: String!
   isActive: Boolean!
   owner: Category!
}

type Player {
   id: ID! @uniquea
   name: String!
   answer: String
   points: Int
}

type Query {
   allQuestions: [Question!]
   allCategories: [Category!]
   allPlayers: [Player!]
}
