type Category {
   id: ID! @unique
   name: String!
   color: String!
}

type Question {
   id: ID! @unique
   question: String!
   type: String!
   category: String!
   answer: String!
   points: Int!
   isActive: Boolean!
}

type Player {
   id: ID! @unique
   name: String!
   answer: String
   points: Int
}

type Query {
   allQuestions: [Question!]
   allCategories: [Category!]
   allPlayers: [Player!]
}
